version: '3.8'

services:
  app:
    container_name: carford
    build: .
    env_file:
      - .env
    depends_on:
      - db
    # environment:
    #   - FLASK_APP=${FLASK_APP}
    #   - FLASK_ENV=${FLASK_ENV}
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  db:
    container_name: carford-db
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DBNAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
